### PR TITLE
Implement admin 'authors' interface

### PR DESCRIPTION
**Pull request by kingjon3377**
This PR includes full CRUD of authors. The only feature obviously lacking at this point is pagination. If another section of the admin interface (or of the app's interface more generally) is merged first, either merging this will require careful handling or this PR should be rebased on top of it, due to the nature of how Angular implements its module system.

### CODE REVIEW

**Review by STOzaki — APPROVED** [review]
Aside from the fact that you do not catch user's mistakes, which I know you have set it as TODO, I think you are good. I like the error catching you did.

**Comment by kingjon3377** [comment]
> Aside from the fact that you do not catch user's mistakes, which I know you have set it as TODO, I think you are good.

Actually, I do catch user error ... I just silently fail instead of notifying the user. Which I had forgotten about, so I'll fix that before merging.

**Comment by STOzaki** [comment]
Oh okay, that makes sense.

**Comment by kingjon3377** [comment]
And that's now done.

**Pull request merged**
